
[general]
# 启用配置文件修改后自动重载
live_config_reload = true

# 窗口设置
[window]
dimensions = { lines = 34, columns = 100 }
padding = { x = 20, y = 20 }
decorations = "full"
opacity = 0.7

# 终端设置
[terminal]
# 启动时使用的Shell
shell = { program = "/bin/zsh", args = ["-l"] }



# 字体设置
[font]
size = 14.0
#normal = { family = "Fira Code", style = "Regular" }
#bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

builtin_box_drawing = true

# 颜色配置
[colors]
primary = { background = "0x1a1b26", foreground = "0xa9b1d6" }


# 光标设置 
[cursor]
style = { shape = "Beam" }
# 简化的光标闪烁设置
# blinking = "On"  

# 鼠标设置
[mouse]
hide_when_typing = false
# 双击和三击阈值使用默认值

# 键盘绑定
[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

# 滚动设置
[scrolling]
history = 10000
multiplier = 3

# 选择设置
[selection]
save_to_clipboard = true
